# Built with Jekyll 3.2.0

# Setup
title:               Ling.craft.
tagline:             'a digital collection for historical linguistic documentation'
description:         'Ling.craft is a collection for colonial linguistic documentation of current Colombia.'
url:                 'http://minicomp.github.io'
baseurl:             '/ed'

# About/contact
author:
  name:              Pilar Ram√≠rez
  url:
  email:             mdelpilar.ramirez@gmail.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
